### ISSUE TITLE
目前是否支持二阶导数？尝试实现MAML失败。

### ISSUE THREAD

**Issue by zhen8838** [MegEngine/MegEngine#115]
## 背景

实现元学习中的经典算法MAML

## 任务描述

初步进行复现。

## 目标

需要对原始模型进行一次推理，然后手动求导并更新参数，将新参数替换原始参数再次进行推理，此时用反向传播进行更新原始参数。

## 问题

我使用megengine r0.6，参考了[learn2learn](https://github.com/learnables/learn2learn)中的[更新方法](https://github.com/learnables/learn2learn/blob/aca4ebf55f383679aaf093f6394776c3424bab2d/learn2learn/utils.py#L227)(他是直接替换原本module对象中的参数)进行实现，但是在megengine中，我替换参数后进行反向传播更新原始传播出现错误，感觉像是计算图断了，又像是没有梯度了？pytorch中grad可以选择是否保留计算图，但这里好像没有看到这个选项。

希望给点实现的建议！

## 例子

```python

import numpy as np
import megengine.functional as F
import megengine.module as M
import megengine as meg
import megengine.optimizer as optim

def replace_parameter(module_table,
                      named_updates):
  for key, value in named_updates.items():
    module_name, param_name = key.rsplit('.', 1)
    exec(f"module_table['{module_name}'].{param_name}=value")


def test_grad_twice():
  # model define
  model = M.Sequential(M.Linear(10, 20),
                       M.Linear(20, 10),
                       M.Linear(10, 5))
  model.train()
  named_param = dict(list(model.named_parameters(requires_grad=True)))
  named_module = dict(list(model.named_children()))
  name_keys = list(named_param.keys())
  params = list(named_param.values())
  loss_fn = F.cross_entropy_with_softmax
  optimizer = optim.SGD(params, lr=0.003)

  # forward once
  optimizer.zero_grad()
  x1 = meg.tensor(np.random.randn(5, 10), dtype='float32')
  y1 = meg.tensor(np.random.randint(0, 5, (5)), dtype='int32')
  loss = loss_fn(model(x1), y1)
  grads = F.grad(loss, params,
                 use_virtual_grad=False,
                  return_zero_for_nodep=False)
  fast_weights = [p - 0.5 * g for g, p in zip(grads, params)]

  # manual update params
  replace_parameter(named_module, dict(zip(name_keys, fast_weights)))

  # forward twice
  x2 = meg.tensor(np.random.randn(5, 10), dtype='float32')
  y2 = meg.tensor(np.random.randint(0, 5, (5)), dtype='int32')
  loss2 = loss_fn(model(x2), y2)
  # got error
  optimizer.backward(loss2)
  optimizer.step()

test_grad_twice()
```

## 错误输出

```sh
Traceback (most recent call last):
  File "/home/zqh/workspace/maml_meg/tests/datafunc/test_omniglot.py", line 207, in <module>
    test_grad_twice()
  File "/home/zqh/workspace/maml_meg/tests/datafunc/test_omniglot.py", line 203, in test_grad_twice
    optimizer.backward(loss2)
  File "/home/zqh/workspace/miniconda3/envs/meg/lib/python3.7/site-packages/megengine/optimizer/optimizer.py", line 175, in backward
    grads = grad_func(loss, params, use_virtual_grad=not cg.is_eager())
  File "/home/zqh/workspace/miniconda3/envs/meg/lib/python3.7/site-packages/megengine/core/tensor.py", line 42, in wrapper
    ret = func(*new_args, **new_kwargs)
  File "/home/zqh/workspace/miniconda3/envs/meg/lib/python3.7/site-packages/megengine/functional/graph.py", line 46, in grad
    return mgb.grad(target, wrt, warn_mid_wrt, use_virtual_grad, return_zero_for_nodep)
  File "/home/zqh/workspace/miniconda3/envs/meg/lib/python3.7/site-packages/megengine/_internal/__init__.py", line 272, in grad
    target, wrts, bool(warn_mid_wrt), use_virtual_grad, return_zero_for_nodep
megengine._internal.exc.MegBrainError: MegBrain core throws exception: mgb::AssertionError
assertion `i.first->dev_tensor_valid()' failed at /home/code/src/core/impl/graph/eager_eval.cpp:197: void mgb::cg::EagerEvalManager::prepare_for_exec(mgb::cg::OperatorNodeBase*)
extra message: var value not valid, but required for opr input: var={id:195, shape:{5,1}, Float32, owner:reduce0(grad[var139:SUB[138]])[194]{Reduce}, name:grad[var137:LOG(reduce0[126])[136]], slot:0, gpu0:0, d, 4, 4} reader=MUL(grad[var198:grad[var127:reduce0[126]]],grad[var137:LOG[136]])[1101]{Elemwise}
+ bt:/home/zqh/workspace/miniconda3/envs/meg/lib/python3.7/site-packages/megengine/_internal/_mgb.cpython-37m-x86_64-linux-gnu.so{1dee859,1e51d82,1ea0a6a,1ea16f6}
| Associated operator: id=1101 name=MUL(grad[var198:grad[var127:reduce0[126]]],grad[var137:LOG[136]])[1101] type=mgb::opr::Elemwise
|   input variables: 
|     0: {id:195, shape:{5,1}, Float32, owner:reduce0(grad[var139:SUB[138]])[194]{Reduce}, name:grad[var137:LOG(reduce0[126])[136]], slot:0, gpu0:0, d, 4, 4}
|     1: {id:1040, layout:{5(1),1(1)}, Float32, owner:reduce0(grad[var202:grad[var125:EXP[124]]])[1039]{Reduce}, name:grad[var198:grad[var127:reduce0(EXP[124])[126]]], slot:0, gpu0:0, d, 4, 8}
|   output variables: 
|     0: {id:1102, shape:{5,1}, Float32, owner:MUL(grad[var198:grad[var127:reduce0[126]]],grad[var137:LOG[136]])[1101]{Elemwise}, name:MUL(grad[var198:grad[var127:reduce0[126]]],grad[var137:LOG[136]])[1101], slot:0, gpu0:0, s, 4, 8}
| 
| Associated operator created by taking grad of: id=197 name=TRUE_DIV(grad[var137:LOG[136]],reduce0[126])[197] type=mgb::opr::Elemwise
|   input variables: 
|     0: {id:195, shape:{5,1}, Float32, owner:reduce0(grad[var139:SUB[138]])[194]{Reduce}, name:grad[var137:LOG(reduce0[126])[136]], slot:0, gpu0:0, d, 4, 4}
|     1: {id:127, layout:{5(1),1(1)}, Float32, owner:reduce0(EXP[124])[126]{Reduce}, name:reduce0(EXP[124])[126], slot:0, gpu0:0, d, 4, 8}
|   output variables: 
|     0: {id:198, shape:{5,1}, Float32, owner:TRUE_DIV(grad[var137:LOG[136]],reduce0[126])[197]{Elemwise}, name:grad[var127:reduce0(EXP[124])[126]], slot:0, gpu0:0, d, 4, 8}
```

**Comment by xpmemeda** [comment]
的确是计算图被打乱了，MegEngine中的每个opr和tensor有绑定关系。建议
`exec(f"module_table['{module_name}'].{param_name}=value")`
替换为
`exec(f"module_table['{module_name}'].{param_name}.set_value(value)")`
也就是在原始的tensor上设置新值。

**Comment by zhen8838** [comment]
这样可以运行，但是计算图不是算法需要的那样。。感觉只能实现定义好计算图，然后每次将权重输入进去算，不过这样也太麻烦了。。

**Comment by zhen8838** [comment]
@xpmemeda 再请教一下如何在使用F.grad后如何保留计算图以进行二阶求导？

**Comment by zhen8838** [comment]
外部加载权重来训练的方法似乎也不行，好像是二阶导数的问题？
```python
class CustomModel3(M.Module):
  def __init__(self) -> None:
    super().__init__()
    self.l1 = M.Linear(10, 20)
    self.l2 = M.Linear(20, 10)
    self.l3 = M.Linear(10, 5)

  def forward(self, x, weights: Dict[str, meg.Tensor] = None):
    x = self.l1._calc_linear(x, weights[1], weights[0])
    x = self.l2._calc_linear(x, weights[3], weights[2])
    x = self.l3._calc_linear(x, weights[5], weights[4])
    return x


@trace
def train_func3(x1, y1, x2, y2, *, loss_fn, opt, net, params):
  loss = loss_fn(net(x1, weights=params), y1)
  grads = F.grad(loss, params, use_virtual_grad=False)
  fast_weights = [p - 0.5 * g for g, p in zip(grads, params)]
  # forward twice
  loss2 = loss_fn(net(x2, weights=fast_weights), y2)
  opt.backward(loss2)


def test_grad_twice_method_3():
  # model define
  model = CustomModel3()
  model.train()
  named_param = dict(list(model.named_parameters(requires_grad=True)))
  params = list(named_param.values())
  external_params = [meg.Parameter(np.random.normal(size=p.shape), dtype='float32') for p in params]

  loss_fn = F.cross_entropy_with_softmax
  optimizer = optim.SGD(external_params, lr=0.003)

  # forward once
  optimizer.zero_grad()
  x1 = meg.tensor(np.random.randn(5, 10), dtype='float32')
  y1 = meg.tensor(np.random.randint(0, 5, (5)), dtype='int32')
  x2 = meg.tensor(np.random.randn(5, 10), dtype='float32')
  y2 = meg.tensor(np.random.randint(0, 5, (5)), dtype='int32')

  train_func3(x1, y1, x2, y2, loss_fn=loss_fn, opt=optimizer,
              net=model, params=external_params)
  optimizer.step()


test_grad_twice_method_3()
```

输出
```sh
megengine._internal.exc.MegBrainError: MegBrain core throws exception: mgb::AssertionError
assertion `i.first->dev_tensor_valid()' failed at /home/code/src/core/impl/graph/eager_eval.cpp:197: void mgb::cg::EagerEvalManager::prepare_for_exec(mgb::cg::OperatorNodeBase*)
extra message: var value not valid, but required for opr input: var={id:195, shape:{5,1}, Float32, owner:reduce0(grad[var139:SUB[138]])[194]{Reduce}, name:grad[var137:LOG(reduce0[126])[136]], slot:0, gpu0:0, d, 4, 4} reader=MUL(grad[var198:grad[var127:reduce0[126]]],grad[var137:LOG[136]])[1101]{Elemwise}
+ bt:/home/zqh/workspace/miniconda3/envs/meg/lib/python3.7/site-packages/megengine/_internal/_mgb.cpython-37m-x86_64-linux-gnu.so{1dee859,1e51d82,1ea0a6a,1ea16f6}
| Associated operator: id=1101 name=MUL(grad[var198:grad[var127:reduce0[126]]],grad[var137:LOG[136]])[1101] type=mgb::opr::Elemwise
|   input variables: 
|     0: {id:195, shape:{5,1}, Float32, owner:reduce0(grad[var139:SUB[138]])[194]{Reduce}, name:grad[var137:LOG(reduce0[126])[136]], slot:0, gpu0:0, d, 4, 4}
|     1: {id:1040, layout:{5(1),1(1)}, Float32, owner:reduce0(grad[var202:grad[var125:EXP[124]]])[1039]{Reduce}, name:grad[var198:grad[var127:reduce0(EXP[124])[126]]], slot:0, gpu0:0, d, 4, 8}
|   output variables: 
|     0: {id:1102, shape:{5,1}, Float32, owner:MUL(grad[var198:grad[var127:reduce0[126]]],grad[var137:LOG[136]])[1101]{Elemwise}, name:MUL(grad[var198:grad[var127:reduce0[126]]],grad[var137:LOG[136]])[1101], slot:0, gpu0:0, s, 4, 8}
| 
| Associated operator created by taking grad of: id=197 name=TRUE_DIV(grad[var137:LOG[136]],reduce0[126])[197] type=mgb::opr::Elemwise
|   input variables: 
|     0: {id:195, shape:{5,1}, Float32, owner:reduce0(grad[var139:SUB[138]])[194]{Reduce}, name:grad[var137:LOG(reduce0[126])[136]], slot:0, gpu0:0, d, 4, 4}
|     1: {id:127, layout:{5(1),1(1)}, Float32, owner:reduce0(EXP[124])[126]{Reduce}, name:reduce0(EXP[124])[126], slot:0, gpu0:0, d, 4, 8}
|   output variables: 
|     0: {id:198, shape:{5,1}, Float32, owner:TRUE_DIV(grad[var137:LOG[136]],reduce0[126])[197]{Elemwise}, name:grad[var127:reduce0(EXP[124])[126]], slot:0, gpu0:0, d, 4, 8}
```

**Comment by xpmemeda** [comment]
目前还没有提供直接求二阶导的函数。
如果需求仍是前面目标中所描述的“需要对原始模型进行一次推理，然后手动求导并更新参数，将新参数替换原始参数再次进行推理，此时用反向传播进行更新原始参数“，那么可以在第一次更新参数时用 set_value 来实现。

**Comment by xxr3376** [comment]
目前已经支持了二阶导，你可以参考这个 test https://github.com/MegEngine/MegEngine/blob/master/imperative/python/test/unit/autodiff/test_grad_manager.py#L337-L352
