### ISSUE TITLE
load_graph 后 OperatorNode 的 params 类型错误

### ISSUE THREAD

**Issue by bigeagle** [MegEngine/MegEngine#135]
## 环境
1.系统环境：ubuntu 18.04
2.MegEngine版本：MegEngine 1.1
3.python版本：3.6.9

## 复现步骤
见代码

## 请提供关键的代码片段便于追查问题

模型见
https://github.com/megvii-research/PMRID/blob/main/models/net_mge.py

先 dump 一个模型出来
```python
from megengine import jit
net = Network()
img = mge.tensor(np.random.randn(1, 4, 64, 64).astype(np.float32))

@jit.trace(capture_as_const=True)
def f(x):
    out = net(x)
    return out

f(img)
f.dump("net.mge", arg_names=['img'])
```

```python
import megengine.core.tensor.megbrain_graph as G
import megengine.utils.comp_graph_tools as cgtools

g = G.load('net.mge')
all_oprs = cgtools.get_opr_seq(g.output_vars_list)

some_opr = all_oprs[25]
print(some_opr.params)
print(type(some_opr.params))   #  这里会是str, 正确应该是 dict
```
![image](https://user-images.githubusercontent.com/548512/103523452-d33df700-4eb6-11eb-99d3-7a8ded0f3ed0.png)

## 请提供完整的日志及报错信息

最典型的情况是使用 megconverter 转换模型格式的时候会出现意外错误

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wangyuzhi/.local/lib/python3.6/site-packages/mgeconvert/utils/convert_onnx.py", line 29, in <module>
    main()
  File "/home/wangyuzhi/.local/lib/python3.6/site-packages/mgeconvert/utils/convert_onnx.py", line 25, in main
    convert_to_onnx(args.input, args.output, graph_name=args.graph, opset=args.opset)
  File "/home/wangyuzhi/.local/lib/python3.6/site-packages/mgeconvert/onnx_converter/onnx_converter.py", line 118, in convert_to_onnx
    net = TopologyNetwork(mge_fpath)
  File "/home/wangyuzhi/.local/lib/python3.6/site-packages/mgeconvert/mge_context/mge_net.py", line 36, in __init__
    self.add_opr(mge_opr)
  File "/home/wangyuzhi/.local/lib/python3.6/site-packages/mgeconvert/mge_context/mge_net.py", line 96, in add_opr
    self.all_oprs_map[x.id] = str_to_mge_class(get_opr_type(x) + "Opr")(x)
  File "/home/wangyuzhi/.local/lib/python3.6/site-packages/mgeconvert/mge_context/mge_op.py", line 309, in __init__
    self.data_format = opr.params["format"]
TypeError: string indices must be integers
```

**Comment by qliu93** [comment]
您好，我来复现一下～

**Comment by bigeagle** [comment]
https://github.com/MegEngine/mgeconvert/issues/4

我仔细看了一下，应该是 mgeconvert 里本身代码有些问题

**Comment by bigeagle** [comment]
这个成为 XY 问题了，我重新提了。
https://github.com/MegEngine/mgeconvert/issues/5
