### ISSUE TITLE
BN 不带 Affine 时设置 freeze 会崩溃

### ISSUE THREAD

**Issue by bigeagle** [MegEngine/MegEngine#145]
## 环境
1.系统环境：ubuntu 18.04
2.MegEngine版本：1.2.0
3.python版本：3.6.3

## 请提供关键的代码片段便于追查问题
```python3
#!/usr/bin/env python3
from typing import Iterable
import numpy as np
import megengine as mge
import megengine.module as M


class Network(M.Module):

    def __init__(self, *, affine=True):
        super().__init__()

        self.conv = M.Conv2d(3, 3, 1, 1, bias=False)
        self.BN = M.BatchNorm2d(3, affine=affine)

    def forward(self, inp):
        x = self.conv(inp)
        return self.BN(x)

    def all_BNs(self) -> Iterable[M.BatchNorm2d]:
        return (m for m in self.modules() if isinstance(m, M.BatchNorm2d))


if __name__ == "__main__":
    img = mge.tensor(np.random.randn(1, 3, 16, 16).astype(np.float32))

    print("BN with Affine")
    net = Network(affine=True)
    out = net(img)
    print("Normal: Pass")

    for BN in net.all_BNs():
        BN.freeze = True

    out = net(img)
    print("Freeze: Pass")

    print("BN without Affine")
    net = Network(affine=False)
    out = net(img)
    print("Normal: Pass")

    for BN in net.all_BNs():
        BN.freeze = True

    out = net(img)
    print("Freeze: Pass")
```

## 请提供完整的日志及报错信息
```
BN with Affine
Normal: Pass
Freeze: Pass
BN without Affine
Normal: Pass
Traceback (most recent call last):
  File "model.py", line 46, in <module>
    out = net(img)
  File "/home/wangyuzhi/.local/lib/python3.6/site-packages/megengine/module/module.py", line 113, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "model.py", line 18, in forward
    return self.BN(x)
  File "/home/wangyuzhi/.local/lib/python3.6/site-packages/megengine/module/module.py", line 113, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/wangyuzhi/.local/lib/python3.6/site-packages/megengine/module/batchnorm.py", line 88, in forward
    scale = self.weight * (self.running_var + self.eps) ** (-0.5)
  File "/home/wangyuzhi/.local/lib/python3.6/site-packages/megengine/core/tensor/array_method.py", line 112, in f
    return _elwise(value, self, mode=mode)
  File "/home/wangyuzhi/.local/lib/python3.6/site-packages/megengine/core/tensor/array_method.py", line 42, in _elwise
    (result,) = apply(op, *args)
TypeError: expect Tensor
```

**Comment by xpmemeda** [comment]
方便问一下使用场景吗，目前这种设置在MegEninge的训练阶段是不被允许的。

如果是在推理阶段，可以使用 net.eval() 来避免报错。

**Comment by bigeagle** [comment]
有的模型需要训到一半freeze住BN，有的BN不需要带affine (后面会再有一些操作之后带上独立的affine)
这种时候理论上应该调用 `track_running_stats=False` ，只是我的代码就得改成
```
if bn.affine:
     bn.freeze = True
else:
     bn.track_running_stats = False
```
比较麻烦。/

**Comment by bigeagle** [comment]
> 如果是在推理阶段，可以使用 net.eval() 来避免报错。

是训练阶段

**Comment by xpmemeda** [comment]
> 有的模型需要训到一半freeze住BN，有的BN不需要带affine (后面会再有一些操作之后带上独立的affine)
> 这种时候理论上应该调用 `track_running_stats=False`

的确不应该这么麻烦，这里 freeze 的时候没有考虑 affine 的不同设置，从而导致 bug。下个版本可以修复。

**Comment by MegChai** [comment]
该 Bug 已经在 MegEngine v1.3 版本修复～ 

[MGE-1954]
