### ISSUE TITLE
无法加载预训练权重

### ISSUE THREAD

**Issue by phoenix0526** [MegEngine/MegEngine#158]
# 环境
1.MegEngine版本：MegEngine 1.2.0
2.python版本：Python 3.8.5
3. Linux服务器：x86_64 、GNU/Linux
## 运行代码：
```
import megengine as mge
from megengine import hub
model_ft = mge.hub.load('megengine/models', 'resnet50', pretrained=True,use_cache=False)
```
## 报错信息：
```
Traceback (most recent call last):
  File "/opt/Anaconda3/envs/MegEngine/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/opt/Anaconda3/envs/MegEngine/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/Anaconda3/envs/MegEngine/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/Anaconda3/envs/MegEngine/lib/python3.7/site-packages/urllib3/connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "/opt/Anaconda3/envs/MegEngine/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 429, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/opt/Anaconda3/envs/MegEngine/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/Anaconda3/envs/MegEngine/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/opt/Anaconda3/envs/MegEngine/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/opt/Anaconda3/envs/MegEngine/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/Anaconda3/envs/MegEngine/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/Anaconda3/envs/MegEngine/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/Anaconda3/envs/MegEngine/lib/python3.7/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /megengine/models/archive/master.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1091)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "try.py", line 10, in <module>
    model_ft = mge.hub.load('megengine/models', 'resnet50', pretrained=True,use_cache=False)
  File "/opt/Anaconda3/envs/MegEngine/lib/python3.7/site-packages/megengine/hub/hub.py", line 203, in load
    hubmodule = _init_hub(repo_info, git_host, use_cache, commit, protocol)
  File "/opt/Anaconda3/envs/MegEngine/lib/python3.7/site-packages/megengine/hub/hub.py", line 121, in _init_hub
    git_host, repo_info, use_cache=use_cache, commit=commit, protocol=protocol
  File "/opt/Anaconda3/envs/MegEngine/lib/python3.7/site-packages/megengine/hub/hub.py", line 74, in _get_repo
    repo_dir = fetcher.fetch(git_host, repo_info, use_cache, commit)
  File "/opt/Anaconda3/envs/MegEngine/lib/python3.7/site-packages/megengine/distributed/helper.py", line 154, in wrapper
    return func(*args, **kwargs)
  File "/opt/Anaconda3/envs/MegEngine/lib/python3.7/site-packages/megengine/hub/fetcher.py", line 266, in fetch
    cls._download_zip_and_extract(archive_url, repo_dir)
  File "/opt/Anaconda3/envs/MegEngine/lib/python3.7/site-packages/megengine/hub/fetcher.py", line 272, in _download_zip_and_extract
    resp = requests.get(url, timeout=HTTP_TIMEOUT, stream=True)
  File "/opt/Anaconda3/envs/MegEngine/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/Anaconda3/envs/MegEngine/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/Anaconda3/envs/MegEngine/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/Anaconda3/envs/MegEngine/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/Anaconda3/envs/MegEngine/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /megengine/models/archive/master.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1091)')))
```

**Comment by xxr3376** [comment]
你好，你的报错显示是你的环境中无法正常访问 github.com 导致，请检查你的网络环境

**Comment by phoenix0526** [comment]
> 你好，你的报错显示是你的环境中无法正常访问 github.com 导致，请检查你的网络环境

老师您好，我通过
wget https://data.megengine.org.cn/models/weights/resnet50_fbaug_76254_4e14b7d1.pkl 将预训练权重文件加载到本地了，将代码改为：
```
model_ft = mge.hub.load('resnet50_fbaug_76254_4e14b7d1.pkl')
```
但是出现如下错误：
```
Traceback (most recent call last):
  File "try.py", line 16, in <module>
    model_ft = mge.hub.load('resnet50_fbaug_76254_4e14b7d1.pkl')
TypeError: load() missing 1 required positional argument: 'entry'
```
想请问老师，函数hub.load()的参数应该如何修改才能正确加载出模型呢

**Comment by xxr3376** [comment]
@phoenix0526 `hub.load` 具体进行的工作不只是去下载一个预训练权重，实际上它做了两件事情

1. 去对应的 github 地址，把 git repo pull 到本地，并解析里面的 Python code
2. 根据 python code，去下载预训练权重

因此你直接把这个 pkl 给 `hub.load` 是不行的，建议你解决一下机器的网络访问问题本身。目前 hub.load 对于网络不通手动下载好的情况暂时还没做处理，欢迎 PR

**Comment by phoenix0526** [comment]
> @phoenix0526 `hub.load` 具体进行的工作不只是去下载一个预训练权重，实际上它做了两件事情
> 
> 1. 去对应的 github 地址，把 git repo pull 到本地，并解析里面的 Python code
> 2. 根据 python code，去下载预训练权重
> 
> 因此你直接把这个 pkl 给 `hub.load` 是不行的，建议你解决一下机器的网络访问问题本身。目前 hub.load 对于网络不通手动下载好的情况暂时还没做处理，欢迎 PR

好的，谢谢老师的指导
