### ISSUE TITLE
Megengine中断时可能会出现进程卡死的情况

### ISSUE THREAD

**Issue by Qsingle** [MegEngine/MegEngine#161]
当使用载入的线程数大于或者等于batch-size进行训练时，如果在中间停顿间歇时执行Ctrl+C中断，则程序可能会卡死，再次执行Ctrl+C则可退出当前Screen激活的环境。
[Classification_megengine.zip](https://github.com/MegEngine/MegEngine/files/6108066/Classification_megengine.zip)

## 环境
1.系统环境：Ubuntu 18.04.5
2.MegEngine版本：1.2.0
3.python版本：3.7.9

## 复现步骤
1.配合screen启动训练程序
2.Ctrl+C中断程序或者程序陷入OOM

## 请提供关键的代码片段便于追查问题
代码见压缩包, 运行脚本的命令如下:
```shell
screen  -S test python train.py --image_folder /data/kaggle/train --train_csv_path ./data/labels_0.4.csv --model_name genet_small --batch_size 8 --num_workers 8 --image_size 192
```

## 请提供完整的日志及报错信息
```shell
^CProcess Process-8:
Traceback (most recent call last):
  File "train.py", line 172, in <module>
    main()
  File "train.py", line 168, in main
Process Process-11:
    train(model, train_loader, val_loader, loss_func)
  File "train.py", line 135, in train
    _train(train_dataloader, model, optimizer, gm, loss_func, epoch)
  File "train.py", line 70, in _train
Process Process-7:
    for i, (x, label) in enumerate(dataloader):
  File "/home/imed/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/data/dataloader.py", line 179, in __next__
    minibatch = self._get_next_batch()
  File "/home/imed/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/data/dataloader.py", line 316, in _get_next_batch
    batch_data = self._try_get_next_batch()
  File "/home/imed/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/data/dataloader.py", line 307, in _try_get_next_batch
    return self.batch_queue.get(timeout=1)
  File "/home/imed/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/data/_queue.py", line 115, in get
    object_id = self.queue.get(block, timeout)
  File "/home/imed/miniconda3/envs/megengine/lib/python3.7/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/home/imed/miniconda3/envs/megengine/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/imed/miniconda3/envs/megengine/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
Traceback (most recent call last):
  File "/home/imed/miniconda3/envs/megengine/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/imed/miniconda3/envs/megengine/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/imed/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/data/dataloader.py", line 729, in _data_selecting_loop
    timeout=MP_QUEUE_GET_TIMEOUT
  File "/home/imed/miniconda3/envs/megengine/lib/python3.7/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/home/imed/miniconda3/envs/megengine/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/imed/miniconda3/envs/megengine/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/imed/miniconda3/envs/megengine/lib/python3.7/multiprocessing/connection.py", line 921, in wait
    ready = selector.select(timeout)
  File "/home/imed/miniconda3/envs/megengine/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
    r = wait([self], timeout)
  File "/home/imed/miniconda3/envs/megengine/lib/python3.7/multiprocessing/connection.py", line 921, in wait
KeyboardInterrupt
    ready = selector.select(timeout)
  File "/home/imed/miniconda3/envs/megengine/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
```

**Comment by fzhangscorec** [comment]
您好，请问用 tmux 还有类似的问题吗？我们在复现和调查这个问题

**Comment by Qsingle** [comment]
> 您好，请问用 tmux 还有类似的问题吗？我们在复现和调查这个问题

您好，感谢对该问题的关注，我用tmux实验了一下，不存在该问题，Screen下只要是在停顿等待数据的间隙Ctrl+C中断就可能出现卡死的情况

**Comment by haolongzhangm** [comment]
may be caused by screen signal handle logic conflict with python runtime singal handle

**Comment by Qsingle** [comment]
链接：https://pan.baidu.com/s/1ag3BSvOU_BMp07q9gB2GMw 
提取码：mege 
可提供的最小数据集如上

**Comment by haolongzhangm** [comment]
dataloader multiprocess issue,    wonfix  after internal discuss
