### ISSUE TITLE
argmax容易出现段错误

### ISSUE THREAD

**Issue by Qsingle** [MegEngine/MegEngine#167]
## 环境
1.系统环境：WIn10
2.MegEngine版本：1.3.1
3.python版本：3.7.9

## 复现步骤
1.创建一个随机Tensor
2.使用Argmax

## 请提供关键的代码片段便于追查问题
```python
import megengine as mge
import megengine.functional as F
import numpy as np
x = mge.tensor(np.random.normal(0,1, (32,5)))
F.argmax(x, axis=-1)
```

## 请提供完整的日志及报错信息
```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\tools\Miniconda3\envs\megengine\lib\site-packages\megengine\tensor.py", line 74, in __new__
    obj = _Tensor.__new__(cls, data, dtype, cn, is_const, no_cache, name)
RuntimeError: assertion `!overflow' failed at ..\..\..\dnn\src/common/utils.h:467: T megdnn::_SafeMultipliesImplUnsigned<unsigned long long>::operator()(const T &, const T &) const [T = unsigned long long]
extra message: multiply overflow: 86861095268864 140730932972811

backtrace:
2 null

3 null

4 null

5 null

6 null

7 null

8 null

9 null

10 null

11 null
```

**Comment by fzhangscorec** [comment]
您好，目前实现中没有处理axis是负数的情形，将会在下一个版本修复这个问题

**Comment by Qsingle** [comment]
好的，感谢

**Comment by megvii-mge** [comment]
您好，此问题已经在v1.4中完成修复：
https://github.com/MegEngine/MegEngine/commit/2c61b8bff4d9b897bcc961bf38f5454f6e1eadc2
