### ISSUE TITLE
使用Profiler生成的json文件不能用profile_analyze分析

### ISSUE THREAD

**Issue by Qsingle** [MegEngine/MegEngine#178]
## 环境
1.系统环境：Ubuntu 18.04
2.MegEngine版本：1.3.1
3.python版本：3.7.9

## 请提供关键的代码片段便于追查问题
```python
import megengine as MGE
from megengine.utils.profiler import Profiler
import numpy as np

x = np.random.normal(size=(1, 3, 512, 512))
x = MGE.tensor(x)
with Profiler():
    out = MGE.module.Conv2d(3, 64, 1, 1)(x)
```
使用以下命令进行分析时会报错
```shell
python3 -m megengine.tools.profile_analyze ./profile.chrome_timeline.json
```

## 请提供完整的日志及报错信息
```shell
Traceback (most recent call last):
  File "/home/imed/miniconda3/envs/megengine/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/imed/miniconda3/envs/megengine/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/imed/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/tools/profile_analyze.py", line 425, in <module>
    main()
  File "/home/imed/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/tools/profile_analyze.py", line 177, in main
    analyzer = ProfileAnalyzer(dump, opr_filter)
  File "/home/imed/miniconda3/envs/megengine/lib/python3.7/site-packages/megengine/utils/profile_analyzer.py", line 184, in __init__
    assert isinstance(obj, dict), type(obj)
AssertionError: <class 'list'>
```
[profile.zip](https://github.com/MegEngine/MegEngine/files/6614102/profile.zip)

**Comment by GetUpEarlier** [comment]
这是因为只有 [静态图下的性能数据](https://megengine.org.cn/doc/stable/zh/user-guide/model-development/profiler.html#id7)能被 `profile_analyze` 解析，动态图下的数据请使用 https://ui.perfetto.dev/#!/ 加载

**Comment by Qsingle** [comment]
好的,谢谢
