### ISSUE TITLE
BUG Issue:'MegEngine/sdk/xor-deploy/xornet.py'在mge1.5.0运行不了但是在1.4.0上可以顺利运行

### ISSUE THREAD

**Issue by MondayZhou** [MegEngine/MegEngine#202]
## 环境
1.系统环境：macOS catelina
2.MegEngine版本：1.5.0
3.python版本：3.8.10

## 复现步骤
1.python ~/Megengine/sdk/xor-deploy/xornet.py

## 请提供关键的代码片段便于追查问题
见**复现步骤**
P.S. 降级到MegEngine1.4.0之后，就可以顺利运行。

## 请提供完整的日志及报错信息
```
Traceback (most recent call last):
  File "xornet.py", line 133, in <module>
    main()
  File "xornet.py", line 81, in main
    _, loss = train_fun(data, label)
  File "xornet.py", line 54, in train_fun
    pred = net(data)
  File "/Users/a123/opt/anaconda3/envs/megengine/lib/python3.8/site-packages/megengine/module/module.py", line 148, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "xornet.py", line 31, in forward
    x = self.fc0(x)
  File "/Users/a123/opt/anaconda3/envs/megengine/lib/python3.8/site-packages/megengine/module/module.py", line 148, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/Users/a123/opt/anaconda3/envs/megengine/lib/python3.8/site-packages/megengine/module/linear.py", line 87, in forward
    return self._calc_linear(x, self.weight, self.bias)
  File "/Users/a123/opt/anaconda3/envs/megengine/lib/python3.8/site-packages/megengine/module/linear.py", line 84, in _calc_linear
    return linear(x, weight, bias, compute_mode=self.compute_mode)
  File "/Users/a123/opt/anaconda3/envs/megengine/lib/python3.8/site-packages/megengine/functional/nn.py", line 104, in linear
    ret = matmul(inp, weight, transpose_b=True, compute_mode=compute_mode)
  File "/Users/a123/opt/anaconda3/envs/megengine/lib/python3.8/site-packages/megengine/functional/math.py", line 891, in matmul
    (result,) = apply(op, inp1, inp2)
TypeError: op MatrixMul expect type Tensor as inputs, got numpy.ndarray actually
```

**Comment by MegChai** [comment]
在 1.5 版本的 [release note](https://github.com/MegEngine/MegEngine/releases/tag/v1.5.0) 中说明了：

> 去掉不必要的隐式类型转换，以解决性能和显存的问题。
> 使用影响：不再接受 numpy array 作为 functional 的 input ，需要转换为MegEngine 的 Tensor 类型。

可以提一个 PR, 将传入 `net` 的 `data` 先转换成 Tensor

```
data = megengine.Tensor(data)
pred = net(data)
```

**Comment by MondayZhou** [comment]
> 在 1.5 版本的 [release note](https://github.com/MegEngine/MegEngine/releases/tag/v1.5.0) 中说明了：
> 
> > 去掉不必要的隐式类型转换，以解决性能和显存的问题。
> > 使用影响：不再接受 numpy array 作为 functional 的 input ，需要转换为MegEngine 的 Tensor 类型。
> 
> 可以提一个 PR, 将传入 `net` 的 `data` 先转换成 Tensor
> 
> ```
> data = megengine.Tensor(data)
> pred = net(data)
> ```

如果我没有理解错的话原文件里的传入网络的data已经是tensor的结构了，以下是部分代码
https://github.com/MegEngine/MegEngine/blob/171d69155a175cda18987b927272eccdcfee3197/sdk/xor-deploy/xornet.py#L92-L110

如有不对望指正。

**Comment by MegChai** [comment]
程序还没跑到你所指的位置就报错中止了哦，第 54 行的代码是在 `train_func` .

https://github.com/MegEngine/MegEngine/blob/171d69155a175cda18987b927272eccdcfee3197/sdk/xor-deploy/xornet.py#L54 

上面给出的代码中, `test_data` 确实在传入 `pred_fun` 前进行了转换，但跑训练的过程中就出错了。

```
Traceback (most recent call last):
  File "xornet.py", line 133, in <module>
    main()
  File "xornet.py", line 81, in main
    _, loss = train_fun(data, label)
  File "xornet.py", line 54, in train_fun
    pred = net(data)
```

在下面这个流程中数据一直是 ndarray 的格式：

train_dataset -> data = minibatch["data"] ->  _, loss = train_fun(data, label)

正确的做法是在 `train_fun` 内对输入 data 做转换，确保计算时使用的是 Tensor.

其实  `pred_fun` 内也应该对输入 data 做转换，确保计算时使用的是 Tensor. 而不是在外部执行这个过程。

**Comment by xxr3376** [comment]
xornet 文件的问题已经修复，关键问题是这两行：https://github.com/MegEngine/MegEngine/blob/master/sdk/xor-deploy/xornet.py#L78-L79
