### ISSUE TITLE
希望能提供 macOS 的 pip 版本

### ISSUE THREAD

**Issue by zxytim** [MegEngine/MegEngine#30]
希望能提供 macOS 版本

## 背景
希望在 macOS 上进行 megengine 的学习和调试。

在 macOS 上安装 megengine 时会出现：
```
2020-03-27 11:30:39 zxytim@localhost Downloads 3001
$ pip3 install megengine -f https://megengine.org.cn/whl/mge.html
2020-03-27 11:30:51 zxytim@localhost Downloads 3001
$ pip3 --version
pip 20.0.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
2020-03-27 11:30:56 zxytim@localhost Downloads 3002
$ pip3 install megengine -f https://megengine.org.cn/whl/mge.html --user --no-cache-dir
Looking in links: https://megengine.org.cn/whl/mge.html
Collecting megengine
  Downloading MegEngine-0.0.1.dev2-py3-none-any.whl (2.8 kB)
Installing collected packages: megengine
Successfully installed megengine-0.0.1.dev2
2020-03-27 11:31:09 zxytim@localhost Downloads 3003
$ python3 -c 'import megengine'
This is an placeholder only, please install by 'pip3 install megengine -f https://megengine.org.cn/whl/mge.html'. Please make sure your pip version is higher than 19.0.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/zxytim/Library/Python/3.7/lib/python/site-packages/megengine/__init__.py", line 3, in <module>
    raise ValueError("This is an placeholder only")
ValueError: This is an placeholder only
```

注意到，wheel 名字是：
```
MegEngine-0.0.1.dev2-py3-none-any.whl
```

作为对比，在一个 Linux 系统下是能正常安装的，且 wheel 名字是：
```
MegEngine-0.3.0-cp36-cp36m-manylinux2010_x86_64.whl 
```

所以看起来是没有打包 macOS 的版本

## 需求描述
希望能提供 macOS 的 pip 版本

**Comment by megvii-mge** [comment]
您好，这一版本暂时只支持 linux 系统，您的需求和建议我们会进行评估，尽快加入我们的迭代计划，感谢您对 MegEngine 项目的关注

**Comment by haolongzhangm** [comment]
@zxytim macos 的whl包，目前版本已经支持， 
未来版本开始会提供构建好的版本供下载的， 目前你着急用的话，可以在你本地构建whl包

详细见： 
scripts/whl/macos/macos_build_whl.sh
scripts/whl/macos/macos_whl_env_prepare.sh
scripts/whl/BUILD_PYTHON_WHL_README.md

**Comment by xxr3376** [comment]
@zxytim 多亏了 @haolongzhangm 的辛苦工作，已经完成第一个版本的打包工作，你可以通过 `pip3 install megengine==1.0.0rc1 -f https://megengine.org.cn/whl/mge.html` 来体验。
