### ISSUE TITLE
F.nn.Pad使用方法

### ISSUE THREAD

**Issue by Qsingle** [MegEngine/MegEngine#405]
`F.nn.pad(x,((1,1))`, 报错`TypeError: 'int' object is not subscriptable`,但是按API来说这种传入应该是没毛病的？
## 环境
1.系统环境：Windows 10
2.MegEngine版本：1.6.0
3.python版本：3.7

## 复现步骤
```python
import megengine as mge
import megengine.functional as F
x = mge.random.normal(size=(1, 179, 27, 27))
x = F.nn.pad(x,((1,1)))
```

## 请提供完整的日志及报错信息
```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\tools\Miniconda3\envs\megengine\lib\site-packages\megengine\functional\nn.py", line 1624, in pad
    p_offsets[i * 2] = pad_witdth[i][0]
TypeError: 'int' object is not subscriptable
```

**Comment by daisycx** [comment]
改成 F.nn.pad(x,((1,1),))可以正常运行

**Comment by Qsingle** [comment]
> 改成 `F.nn.pad(x,((1,1),))`可以正常运行，python会把 `((1, 1))` 解析成 `(1,1)`

好的，感谢
