### ISSUE TITLE
[BUG Issue] tensor.shape报错

### ISSUE THREAD

**Issue by Asthestarsfalll** [MegEngine/MegEngine#475]
## 环境
1.系统环境：MegStudio
2.MegEngine版本：1.9.0
3.python版本：3.7.12

## 复现步骤
repo地址:https://github.com/Asthestarsfalll/UniFormer-MegEngine
报错在Attention类的forward中，单独运行没有问题，当使用Uniformer类时会报错：

![image](https://user-images.githubusercontent.com/72954905/184311837-86b73743-a97e-4f4a-8f24-aae64306f7e6.png)

报错位置：https://github.com/Asthestarsfalll/UniFormer-MegEngine/blob/main/image_classification/models/uniformer.py#L100

可以直接运行image_classification文件夹中的compare.py

**Comment by gaohuazuo** [comment]
应该是你的 PatchEmb 的 LayerNorm 的 normalized_shape 设错了，应该是 (64, 56, 56) 但是被设成了 (64,)。请按照错误提示

> Hint: This is where it is reported, not where it happened. You may call `megengine.config.async_level = 0 to get better error reporting.

设置 mge.config.async_level = 0 之后不难发现是 layer norm 的问题

**Comment by Asthestarsfalll** [comment]
你好，确实是设置错了，感谢帮助！
但是我设置mge.config.async_level = 0似乎没有什么变化。
另外有一点疑问，请问报错这样设置有什么原因呢？最直观的原因最先展示不是更好吗，我发现有很多情况下megengine的报错都不好直接的找出原因。

**Comment by gaohuazuo** [comment]
以这次的报错为例

```text
RuntimeError: assertion `data.shape[unnormalized_dim + i] == weight.shape[i]' failed at ../../../../../../dnn/src/common/layer_norm.cpp:78: void megdnn::LayerNormBase::check_layout_fwd(const megdnn::TensorLayout&, const megdnn::TensorLayout&, const megdnn::TensorLayout&, const megdnn::TensorLayout&, const megdnn::TensorLayout&, const megdnn::TensorLayout&)                                                                                                                  
extra message: data={2(200704),64(3136),56(56),56(1) Float32}, weight={64(1) Float32}, bias={64(1) Float32}, dst={2(200704),64(3136),56(56),56(1) Float32}, mean={2(3584),64(56),56(1) Float32}, rstd={2(3584),64(56),56(1) Float32}        
                                                                                                                      
backtrace:                                                                                                            
/home/gaohuazuo/.local/lib/python3.9/site-packages/megengine/core/lib/libmegengine_shared.so(_ZN3mgb13MegBrainErrorC1ERKSs+0x4a) [0x7feb4467775a]                                                                                           
/home/gaohuazuo/.local/lib/python3.9/site-packages/megengine/core/lib/libmegengine_shared.so(+0x27efab7) [0x7feb446deab7]                                                                                                                   
/home/gaohuazuo/.local/lib/python3.9/site-packages/megengine/core/lib/libmegengine_shared.so(_ZN6megdnn12ErrorHandler15on_megdnn_errorERKSs+0x14) [0x7feb47a65c04]                                                                          
/home/gaohuazuo/.local/lib/python3.9/site-packages/megengine/core/lib/libmegengine_shared.so(_ZN6megdnn12ErrorHandler15on_megdnn_errorEPKc+0x22) [0x7feb47a67702]                                                                           
/home/gaohuazuo/.local/lib/python3.9/site-packages/megengine/core/lib/libmegengine_shared.so(_ZN6megdnn15__assert_fail__EPKciS1_S1_S1_z+0x190) [0x7feb47b052e0]                                                                             
/home/gaohuazuo/.local/lib/python3.9/site-packages/megengine/core/lib/libmegengine_shared.so(_ZN6megdnn13LayerNormBase16check_layout_fwdERKNS_12TensorLayoutES3_S3_S3_S3_S3_+0x879) [0x7feb47ab18f9]                                        
/home/gaohuazuo/.local/lib/python3.9/site-packages/megengine/core/lib/libmegengine_shared.so(_ZN6megdnn16LayerNormForward10check_execERKNS_12TensorLayoutES3_S3_S3_S3_S3_m+0x29) [0x7feb47ab19a9]                                           
/home/gaohuazuo/.local/lib/python3.9/site-packages/megengine/core/lib/libmegengine_shared.so(_ZN6megdnn4cuda20LayerNormForwardImpl4execERKNS_8TensorNDES4_S4_S4_S4_S4_RKNS_9WorkspaceE+0x36) [0x7feb4a2cc476]                               
/home/gaohuazuo/.local/lib/python3.9/site-packages/megengine/core/_imperative_rt.cpython-39-x86_64-linux-gnu.so(+0x33d134) [0x7febb99cb134]                                                                                                 
/home/gaohuazuo/.local/lib/python3.9/site-packages/megengine/core/_imperative_rt.cpython-39-x86_64-linux-gnu.so(+0x2d16a5) [0x7febb995f6a5]                                                                                                 
                                                                                                                      
                                                                                                                      
The above exception was the direct cause of the following exception:                                                  
                                                                                                                      
Traceback (most recent call last):                                                                                    
  File "/home/gaohuazuo/Downloads/UniFormer-MegEngine/image_classification/compare.py", line 63, in <module>          
    mge_out = mge_model(mge_inp)                                                                                      
  File "/home/gaohuazuo/.local/lib/python3.9/site-packages/megengine/module/module.py", line 142, in __call__         
    outputs = self.forward(*inputs, **kwargs)                                                                         
  File "/home/gaohuazuo/Downloads/UniFormer-MegEngine/image_classification/models/uniformer.py", line 329, in forward 
    x = self.forward_features(x)                                                                                      
  File "/home/gaohuazuo/Downloads/UniFormer-MegEngine/image_classification/models/uniformer.py", line 311, in forward_features                                                                                                              
    x = self.patch_embed1(x)                                                                                          
  File "/home/gaohuazuo/.local/lib/python3.9/site-packages/megengine/module/module.py", line 142, in __call__         
    outputs = self.forward(*inputs, **kwargs)                                                                         
  File "/home/gaohuazuo/Downloads/UniFormer-MegEngine/image_classification/models/vision_transformer.py", line 40, in forward                                                                                                               
    x = self.norm(x)                                                                                                  
  File "/home/gaohuazuo/.local/lib/python3.9/site-packages/megengine/module/module.py", line 142, in __call__         
    outputs = self.forward(*inputs, **kwargs)                                                                         
  File "/home/gaohuazuo/.local/lib/python3.9/site-packages/megengine/module/normalization.py", line 135, in forward   
    x = F.nn.layer_norm(                                                                                              
  File "/home/gaohuazuo/.local/lib/python3.9/site-packages/megengine/functional/nn.py", line 1161, in layer_norm      
    return apply(op, inp, weight, bias)[0]                                                                            
megengine.core._imperative_rt.core2.AsyncError: An async error is reported. See above for the actual cause. Hint: This is where it is reported, not where it happened. You may call `megengine.config.async_level = 0 to get better error reporting.
```

第一个 exception 的 message 包含错误的直接原因
1. 失败的 assert 语句 `data.shape[unnormalized_dim + i] == weight.shape[i]`
2. assert 语句所在的 cpp 文件 `dnn/src/common/layer_norm.cpp:78: void megdnn::LayerNormBase::check_layout_fwd`
3. c++ backtrace

exception 展示的结构是

```text
RuntimeError: <direct cause of error>

The above exception was the direct cause of the following exception:

<Python traceback, only accurate if async_level == 0>

AsyncError: An async error is reported...
```

这是按照 Python exception chaining 语义的结果，所以阅读方法应该类似下面的例子

```python
try:
    1 / 0
except:
    assert 0
```

```text
ZeroDivisionError                         Traceback (most recent call last)
Input In [1], in <module>
      1 try:
----> 2     1 / 0
      3 except:

ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

AssertionError                            Traceback (most recent call last)
Input In [1], in <module>
      2     1 / 0
      3 except:
----> 4     assert 0

AssertionError:
```

你想要的可能是

```text
<Python traceback>

RuntimeError: <direct cause of error>
```

这种展示方式在 async_level = 0 时是合理的，之后会改成 async_level = 0 时以这种方式展示。而 async_level > 0 时这种形式不符合语义，所以 async_level > 0 时会保持现在的 exception chaining 形式。

**Comment by Asthestarsfalll** [comment]
好的，感谢回复！对这些确实不太了解，或许可以添加在官方文档中？
