### ISSUE TITLE
BatchNorm2d层添加报错

### ISSUE THREAD

**Issue by Yoline777** [MegEngine/MegEngine#96]
使用[官方GAN](https://github.com/MegEngine/Models/tree/master/official/vision/gan)代码可以正常训练
```
class WGANDiscriminatorCIFAR(wgan_base.WGANBaseDiscriminator):
    r"""
    ResNet backbone discriminator for ResNet WGAN.

    Attributes:
        ndf (int): Variable controlling discriminator feature map sizes.
        loss_type (str): Name of loss to use for GAN loss.
    """
    def __init__(self, ndf=128, **kwargs):
        super().__init__(ndf=ndf, **kwargs)

        # Build layers
        self.block1 = DBlockOptimized(3, self.ndf)
        self.block2 = DBlock(self.ndf,
                             self.ndf,
                             downsample=True)
        self.conv = M.Conv2d(self.ndf, self.ndf, 3, 1, 1)
        self.bn = M.BatchNorm2d(self.ndf, affine=True)
        self.block3 = DBlock(self.ndf,
                             self.ndf,
                             downsample=False)
        self.block4 = DBlock(self.ndf,
                             self.ndf,
                             downsample=False)
        self.l5 = M.Linear(self.ndf, 1)
        self.activation = M.ReLU()

        # Initialise the weights
        M.init.xavier_uniform_(self.l5.weight, 1.0)

    def forward(self, x):
        r"""
        Feedforwards a batch of real/fake images and produces a batch of GAN logits.

        Args:
            x (Tensor): A batch of images of shape (N, C, H, W).

        Returns:
            Tensor: A batch of GAN logits of shape (N, 1).
        """
        h = x
        h = self.block1(h)
        h = self.block2(h)
        h = self.conv(h)
        h = self.bn(h)
        h = self.block3(h)
```
conv和bn为手动添加的层。添加后报错：
```
megengine._internal.exc.MegBrainError: MegBrain core throws exception: mgb::GraphError
variable shared[301] force updated by two oprs: batch_norm(ADD[18579],reshape[295],reshape[299],shared[301],shared[303])[18581]{BatchNormForward} batch_norm(virtual_dep[19272],reshape[295],reshape[299],shared[301],...)[19274]{BatchNormForward}
+ bt:/home/user/.conda/envs/me_ly/lib/python3.7/site-packages/megengine/_internal/_mgb.cpython-37m-x86_64-linux-gnu.so{1eef4c5,1eeefe1,1eef152,1ef1b9f}
```
请问是BN的使用方法错误了么，还是有注意事项被我忽略了

**Comment by Yoline777** [comment]
```
INFO: Starting training from global step 0...
Traceback (most recent call last):
  File "/data3/yoline/METest/train_wgan.py", line 35, in <module>
    trainer.train()
  File "/data3/yoline/METest/megengine_mimicry/training/trainer.py", line 271, in train
    optD=self.optD)
  File "/data3/yoline/METest/megengine_mimicry/nets/wgan/wgan_base.py", line 56, in _
    ret = traced_obj(*args, **kwargs)
  File "/home/user/.conda/envs/me_ly/lib/python3.7/site-packages/megengine/jit/__init__.py", line 427, in __call__
    self._do_trace()
  File "/home/user/.conda/envs/me_ly/lib/python3.7/site-packages/megengine/jit/__init__.py", line 402, in _do_trace
    self._compiled_func = graph.get_default_graph().compile(None, self._outspec)
  File "/home/user/.conda/envs/me_ly/lib/python3.7/site-packages/megengine/_internal/mgb.py", line 1614, in compile
    ret = self._do_compile(copy, optimize_for_inference)
  File "/home/user/.conda/envs/me_ly/lib/python3.7/site-packages/megengine/_internal/mgb.py", line 1472, in _do_compile
    return _mgb.CompGraph__do_compile(self, copy, optimize_for_inference)
megengine._internal.exc.MegBrainError: MegBrain core throws exception: mgb::GraphError
variable shared[301] force updated by two oprs: batch_norm(ADD[18579],reshape[295],reshape[299],shared[301],shared[303])[18581]{BatchNormForward} batch_norm(virtual_dep[19272],reshape[295],reshape[299],shared[301],...)[19274]{BatchNormForward}
+ bt:/home/user/.conda/envs/me_ly/lib/python3.7/site-packages/megengine/_internal/_mgb.cpython-37m-x86_64-linux-gnu.so{1eef4c5,1eeefe1,1eef152,1ef1b9f}

Process finished with exit code 1
```
完整的错误信息

**Comment by lixiangyin666** [comment]
我先复现一下啊

**Comment by lixiangyin666** [comment]
@Yoline777 这边可以复现，应该是个bug，我们先跟踪一下

**Comment by Yoline777** [comment]
@dc3671 这个bug处理好了么

**Comment by Songtingt** [comment]
相同的错误，请问解决好了么

**Comment by MegChai** [comment]
> 相同的错误，请问解决好了么

请升级到 megengine 1.0 正式版本使用， @trace 时不添加 `symbolic=True` ，看是否能正常运行

**Comment by MegChai** [comment]
@Yoline777 @Songtingt 该 Bug 已经修复，在 1.1 版本中 `@trace(symbolic=True)` 时 BatchNorm2d 亦可被正常连续使用多次，在获取最新版本前，请暂时将 `symbolic` 设置为 `False`.

**Comment by Songtingt** [comment]
> @Yoline777 @Songtingt 该 Bug 已经修复，在 1.1 版本中 `@trace(symbolic=True)` 时 BatchNorm2d 亦可被正常连续使用多次，在获取最新版本前，请暂时将 `symbolic` 设置为 `False`.
非常感谢！

**Comment by megvii-mge** [comment]
1.1 版本已发布，此 Issue Closed.
